### ISSUE TITLE
region parameter

### ISSUE THREAD

**Issue by anker-shady** [doppelganger113/amazon-pay-react#1]
i recommend add region parameter in this react component
![image](https://user-images.githubusercontent.com/13210731/47469345-0a261600-d833-11e8-9f15-2773f2c10c7a.png)

**Comment by doppelganger113** [comment]
@anker-shady sorry for late response, was sick last week. Updated to version **v0.7.1** and published to npm with changes included and tested locally for region changes.

PR https://github.com/doppelganger113/amazon-pay-react/pull/3

Closing the ticket.
